#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $ADMIN_NAME CREATEDB LOGIN PASSWORD '$ADMIN_PASSWORD';
    CREATE DATABASE $DATABASE_NAME WITH ENCODING='UTF8' OWNER='$ADMIN_NAME';
EOSQL

echo ""
echo "INIT DATBASE: DONE"
echo ""
